spec:
  destination:
    # HIGHLIGHT
    server: https://kubernetes.default.svc
    namespace: default # Specify target namespace here
  source:
    # HIGHLIGHT
    repoURL: https://github.com/anonymous-peasant/argocd-app-of-apps-playground.git
    # HIGHLIGHT
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

# HIGHLIGHT
applications:
  - name: carts
  - name: catalogue
  - name: frontend
  - name: orders
  - name: payment
  - name: queue-master
  - name: rabbitmq
  - name: session-db
  - name: shipping
  - name: user
