spec:
  destination:
    # HIGHLIGHT
    server: https://kubernetes.default.svc
  source:
    # HIGHLIGHT
    repoURL: https://github.com/anonymous-peasant/argocd-app-of-apps-playground.git
    # HIGHLIGHT
    targetRevision: main

# HIGHLIGHT
applications:
  - name: carts
  - name: catalogue
  - name: frontend
  - name: orders
  - name: payment
  - name: queue-master
  - name: rabbitmq
  - name: session-db
  - name: shipping
  - name: user
