---
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    name: orders
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    name: orders
